
package org.paulmarquardt.setTheory;

import junit.framework.TestCase;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Logger;
import java.util.stream.*;

import org.json.JSONObject;

import org.paulmarquardt.setTheory.utils.SequenceUtils;

public class TestSequenceUtils extends TestCase {

	List<PitchClassSequence> testPSeqs = new ArrayList<PitchClassSequence>();
	String testFileName = "com/newscores/setTheory/TestSequenceUtilsData.json";
	String testJson = new String();


	protected void setUp() throws Exception {
		super.setUp();
		this.testJson = new String();
		try
		{
			String testFilePath = Thread.currentThread().getContextClassLoader().getResource(testFileName).getFile();
			testJson = new String ( Files.readAllBytes( Paths.get(testFilePath) ) );
			assertTrue("Ensure that JSON data is populated",testJson.length() > 0 );
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}

	public void testRandomSequences() {
		int numberOfRandomSeqs = 100;
		int maxSize = 12;
		int count = 0;
		int numOnes = 0;
		System.out.println( "Test random PitchClassSequences without repeated pcs." );
		IntStream.rangeClosed(0, maxSize).forEach( length -> {
			IntStream.rangeClosed(0, numberOfRandomSeqs).forEach( i ->  {
				PitchClassSequence pcSeq = SequenceUtils.getRandomPitchClassSequence(length, true);
				System.out.println(
					String.format("Random unique PitchClassSequence of size %d: %s",
						length,
							pcSeq.toString() )
				);
			});
		});
		System.out.println( "Test random PitchSequences which can contain repeated pcs." );
		Random randGen = new Random();
		IntStream.rangeClosed(0, maxSize * 2).forEach( length -> {
			IntStream.rangeClosed(0, numberOfRandomSeqs).forEach( i ->  {
				final int minPitch = randGen.nextInt(24);
				final int maxPitch = minPitch + randGen.nextInt(80);
				PitchSequence randomPitchSequence = SequenceUtils.getRandomPitchSequence(length, minPitch, maxPitch, false);
				System.out.println(
					String.format("Random unique PitchSequence of size %d in the range %d to %d: %s",
						length,
						minPitch,
						maxPitch, randomPitchSequence.toString()
					)
				);
				for ( int pitch : randomPitchSequence.getMembers() ) {
					assertTrue("Testing that upper and lower bounds are met", pitch >= minPitch && pitch <= maxPitch);
				}
			});
		});	
	}

	/*
	This test tests weird behavior where sequences generated by getRandomPitchSequence() never contain a consecutive interval of 1.
	 */
	public void testShuffle() {
		int numberOfTests = 1000;
		int maxSize = 12;
		int count = 0;
		AtomicInteger numOnes = new AtomicInteger();
		IntStream.range(0, numberOfTests).forEach( i ->  {
			List<Integer> testList = new ArrayList<Integer>();
			IntStream.range(0, maxSize).forEach( j ->  {
				testList.add(j);
			});
			IntStream.range(0, testList.size() - 1).forEach( k ->  {
					if ( testList.get(k+1) - testList.get(k) == 1 ) {
						numOnes.addAndGet(1);
					}
			});
		});
		assertTrue("Testing that random sequences contain at least one consecutive pair where m[n+1] - m[n] == 1", numOnes.get() > 0);
	}

	public void testEmbeddedSequences() {
		JSONObject tlJson = new JSONObject(this.testJson);
		Logger testLogger = Logger.getLogger(this.getClass().getName());
		testLogger.info(tlJson.getJSONObject("EmbeddedTestA").toString() );
		//JSONString test = tlJson.getString("EmbeddedTestA");
		PitchClassSequence testSeqA = ObjectSerializers.pitchClassSequenceJsonDeserializer(tlJson.getJSONObject("EmbeddedTestA").toString());
		PitchClassSequence testSeqMasterA = ObjectSerializers.pitchClassSequenceJsonDeserializer(tlJson.getJSONObject("EmbeddedMasterA1").toString());
		testLogger.info(testSeqA.toString());
		testLogger.info(testSeqMasterA.toString());
		SequenceUtils.getEmbeddedSubsequences(testSeqMasterA, testSeqA);
		assert ( testSeqA.getMembers().size() > 0);
		assert ( testSeqMasterA.getMembers().size() > 0);
	}
}
